CREATE TABLE [dbo].[FACT_SALES] (
    [SaleID] INT IDENTITY(1,1) NOT NULL,
    
    [CustomerID] NVARCHAR(5) NOT NULL,
    [ProductID] INT NOT NULL,
    [EmployeeID] INT NOT NULL,
    [ShipperID] INT NOT NULL,
    [DateID] INT NOT NULL,

    [Quantity] INT NOT NULL,
    [UnitPrice] DECIMAL(10,2) NOT NULL,
    [Discount] DECIMAL(5,2) NOT NULL,
    [TotalAmount] DECIMAL(12,2) NOT NULL,

    CONSTRAINT PK_FACT_SALES
        PRIMARY KEY (SaleID),

    CONSTRAINT FK_FACT_SALES_CUSTOMER
        FOREIGN KEY (CustomerID)
        REFERENCES DIM_CUSTOMER(CustomerID),

    CONSTRAINT FK_FACT_SALES_PRODUCT
        FOREIGN KEY (ProductID)
        REFERENCES DIM_PRODUCT(ProductID),

    CONSTRAINT FK_FACT_SALES_EMPLOYEE
        FOREIGN KEY (EmployeeID)
        REFERENCES DIM_EMPLOYEE(EmployeeID),

    CONSTRAINT FK_FACT_SALES_SHIPPER
        FOREIGN KEY (ShipperID)
        REFERENCES DIM_SHIPPER(ShipperID),

    CONSTRAINT FK_FACT_SALES_DATE
        FOREIGN KEY (DateID)
        REFERENCES DIM_DATE(DateID)
);